default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

actions:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV.fetch('PG_DATABASE', 'postgres') %>
  host:     <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'password') %>
  port:     <%= ENV.fetch('PG_PORT', 5432) %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV.fetch('PG_DATABASE', 'postgres') %>
  host: <%= ENV.fetch('PG_HOST',  'localhost') %>
  username: <%= ENV.fetch('PG_USER', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'password') %>
  port: <%= ENV.fetch('PG_PORT', 5432) %>
