name: TESTES
on: [push, pull_request]

jobs:
  testes-rails-cucumber:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: password

    steps:
      - name: Checando o codigo
        uses: actions/checkout@v2

      - name: Configurando o Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - name: Instalando um Cliente PostgreSQL
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Instalando as Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Inicializando o Banco de Dados de Testes
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
        run: |
          bundle exec rails db:prepare
      - name: Realizando testes unitarios
        run: | 
          bundle exec rails test:models
      - name: Realizando testes de cenario
        run: | 
          bundle exec cucumber
